theme: jekyll-theme-hacker
title: Welcome to Sinister 6 Studios!
description: Feel free to check out our new games and projects
description: The Last Step of Time
description: Join Chronos Kid as he battles through different eras in time to defeat The Last Order in their attempt to take over the world!
